//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.07 at 12:37:27 PM EST 
//


package com.juliocrosario.exam.model.user;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for exam complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="exam">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="test1" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="test2" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="test3" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "exam", propOrder = {
    "test1",
    "test2",
    "test3"
})
public class Exam {

    protected double test1;
    protected double test2;
    protected double test3;

    /**
     * Gets the value of the test1 property.
     * 
     */
    public double getTest1() {
        return test1;
    }

    /**
     * Sets the value of the test1 property.
     * 
     */
    public void setTest1(double value) {
        this.test1 = value;
    }

    /**
     * Gets the value of the test2 property.
     * 
     */
    public double getTest2() {
        return test2;
    }

    /**
     * Sets the value of the test2 property.
     * 
     */
    public void setTest2(double value) {
        this.test2 = value;
    }

    /**
     * Gets the value of the test3 property.
     * 
     */
    public double getTest3() {
        return test3;
    }

    /**
     * Sets the value of the test3 property.
     * 
     */
    public void setTest3(double value) {
        this.test3 = value;
    }

    @Override
    public String toString() {
        return "Exam{" +
                "test1=" + test1 +
                ", test2=" + test2 +
                ", test3=" + test3 +
                '}';
    }
}
